CREATE OR REPLACE VIEW vw_reservation AS
SELECT
    RESERVATION_ID,
    COUNTRY,
    TRIP_DATE,
    TRIP_NAME,
    FIRSTNAME,
    LASTNAME,
    STATUS,
    RESERVATION.TRIP_ID,
    RESERVATION.PERSON_ID,
    NO_TICKETS
FROM RESERVATION
JOIN TRIP ON RESERVATION.TRIP_ID = TRIP.TRIP_ID
JOIN PERSON ON RESERVATION.PERSON_ID = PERSON.PERSON_ID;

CREATE OR REPLACE VIEW vw_trip AS
SELECT
    T.TRIP_ID,
    T.COUNTRY,
    T.TRIP_DATE,
    T.TRIP_NAME,
    T.MAX_NO_PLACES,
    (T.MAX_NO_PLACES - COALESCE(SUM(R.NO_TICKETS), 0)) AS no_available_places
FROM TRIP T
LEFT JOIN RESERVATION R ON T.TRIP_ID = R.TRIP_ID AND STATUS IN ('N', 'P')
GROUP BY T.TRIP_ID, T.COUNTRY, T.TRIP_DATE, T.TRIP_NAME, T.MAX_NO_PLACES;

CREATE OR REPLACE VIEW vw_available_trip AS
SELECT
    T.TRIP_ID,
    T.COUNTRY,
    T.TRIP_DATE,
    T.TRIP_NAME,
    T.MAX_NO_PLACES,
    (T.MAX_NO_PLACES - COALESCE(SUM(R.NO_TICKETS), 0)) AS no_available_places
FROM TRIP T
LEFT JOIN RESERVATION R ON T.TRIP_ID = R.TRIP_ID AND STATUS IN ('N', 'P')
WHERE T.TRIP_DATE > CURRENT_DATE
GROUP BY T.TRIP_ID, T.COUNTRY, T.TRIP_DATE, T.TRIP_NAME, T.MAX_NO_PLACES
HAVING (T.MAX_NO_PLACES - COALESCE(SUM(R.NO_TICKETS), 0)) > 0;